### ISSUE TITLE
RootController Not found

### ISSUE THREAD

**Issue by piyushtour** [PubMatic/ios-openwrap-sdk-samples#12]
OpenWrapSDK v3.4.1 & OpenWrapSDK v3.5.0

How to Find RootController like GAMBannerView inside POBBannerView?
![Screenshot 2024-05-06 at 12 14 38 PM](https://github.com/PubMatic/ios-openwrap-sdk-samples/assets/109497664/aa001858-3e2b-44b8-b4d2-ef7e905baf7d)

**Comment by pm-preety-narvekar** [comment]
Yes, there is required method in `POBBannerViewDelegate` delegate as 
```
//Provides a view controller to use for presenting model views
- (UIViewController *)bannerViewPresentationController {
    return self;
}
```
You need to implement this.
